version: "3.7"
services:
  app:
    image: thuicetea/module_detection:v1
    container_name: module-detection-app
    restart: always
    ports: 
      - 8080:80
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
