version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: .docker/Dockerfile
    image: thuicetea/module_detection:model-version-one
    container_name: module-detection-app
    restart: always
    ports: 
      - 8080:80
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
